package api

import "net/http"

func RegisterRoutes(mux *http.ServeMux) {
	mux.HandleFunc("/api/status", StatusHandler)
	mux.HandleFunc("/api/login", LoginHandler)
	mux.HandleFunc("/api/logout", RequireAuth(LogoutHandler))
	mux.HandleFunc("/api/settings/language", LanguageSettingsHandler)
	mux.HandleFunc("/api/auth/mode", RequireAuth(AuthModeHandler))
	mux.HandleFunc("/api/auth/health", RequireAuth(AuthHealthHandler))
	mux.HandleFunc("/api/auth/password", RequireAuth(ChangeLocalPasswordHandler))
	mux.HandleFunc("/api/auth/username", RequireAuth(ChangeLocalUsernameHandler))
	mux.HandleFunc("/api/framework/info", RequireAuth(FrameworkInfoHandler))
	mux.HandleFunc("/api/framework/settings", RequireAuth(FrameworkSettingsHandler))
	mux.HandleFunc("/api/framework/restart", RequireAuth(FrameworkRestartHandler))
	mux.HandleFunc("/api/framework/announcement", RequireAuth(FrameworkAnnouncementHandler))
	mux.HandleFunc("/api/bot/status", RequireAuth(BotStatusHandler))
	mux.HandleFunc("/api/bot/action", RequireAuth(BotActionHandler))
	mux.HandleFunc("/api/bot/watchdog/status", RequireAuth(BotWatchdogStatusHandler))
	mux.HandleFunc("/api/bot/watchdog/action", RequireAuth(BotWatchdogActionHandler))
	mux.HandleFunc("/api/bot/system", RequireAuth(BotSystemInfoHandler))
	mux.HandleFunc("/api/bot/logs", RequireAuth(BotLogsHandler))
	mux.HandleFunc("/api/ts3/connection/status", RequireAuth(TS3ConnectionStatusHandler))
	mux.HandleFunc("/api/ts3/connection/test", RequireAuth(TS3ConnectionTestHandler))
	mux.HandleFunc("/api/settings/ts3", RequireAuth(TS3SettingsHandler))
	mux.HandleFunc("/api/settings/discord", RequireAuth(DiscordSettingsHandler))
	mux.HandleFunc("/api/settings/discord/channels", RequireAuth(DiscordChannelsHandler))
	mux.HandleFunc("/api/settings/discord/roles", RequireAuth(DiscordRolesHandler))
	mux.HandleFunc("/api/settings/ts3/channels", RequireAuth(TS3ChannelsHandler))
	mux.HandleFunc("/api/settings/ts3/servergroups", RequireAuth(TS3ServerGroupsHandler))
	mux.HandleFunc("/api/support/settings", RequireAuth(SupportSettingsHandler))
	mux.HandleFunc("/api/support/status", RequireAuth(SupportStatusHandler))
	mux.HandleFunc("/api/support/action", RequireAuth(SupportActionHandler))
	mux.HandleFunc("/api/announcement/settings", RequireAuth(AnnouncementSettingsHandler))
	mux.HandleFunc("/api/announcement/status", RequireAuth(AnnouncementStatusHandler))
	mux.HandleFunc("/api/announcement/send", RequireAuth(AnnouncementSendHandler))
	mux.HandleFunc("/api/stats", RequireAuth(StatsHandler))
	mux.HandleFunc("/api/plugins", RequireAuth(PluginsHandler))
	mux.HandleFunc("/api/plugins/toggle", RequireAuth(TogglePluginHandler))
	mux.HandleFunc("/api/plugins/config", RequireAuth(PluginConfigHandler))
}
